export const ciclesData = {
  smx: {
    titol: "Tècnic  en Sistemes Microinformàtics i Xarxes",
    descripcio: "SMX",
    alerta:
      "Procés d'admissió: del 20/05 al 28/05<br>Matrícula telemàtica: del 20/07 al 27/07",
pla: [
  '<div class="panel-section">',
  "<h3>📚 Pla de formació de 2000 hores</h3>",
  "<h4>· Incloses 500 h de Formació en Empresa</h4>",
  '<div class="plan-formacio">',

  '<div class="curs">',
  "<h4>1r curs</h4>",
  "<ul>",
  "<li>Muntatge i manteniment d’equips (7 h/setm)</li>",
  "<li>Sistemes operatius monoposat (4 h/setm)</li>",
  "<li>Aplicacions ofimàtiques (7 h/setm)</li>",
  "<li>Xarxes locals (7 h/setm)</li>",
  "<li>Anglés professional (GM) (2 h/setm)</li>",
  "<li>Itinerari personal per a l’ocupabilitat I (3 h/setm)</li>",
  "</ul>",
  "</div>",

  '<div class="curs">',
  "<h4>2n curs</h4>",
  "<ul>",
  "<li>Sistemes operatius en xarxa (6 h/setm)</li>",
  "<li>Seguretat informàtica (4 h/setm)</li>",
  "<li>Serveis en xarxa (7 h/setm)</li>",
  "<li>Aplicacions web (3 h/setm)</li>",
  "<li>Mòdul optatiu (3 h/setm)</li>",
  "<li>Itinerari personal per a l’ocupabilitat II (3 h/setm)</li>",
  "<li>Sostenibilitat aplicada al sistema productiu (1 h/setm)</li>",
  "<li>Digitalització aplicada al sistema productiu (1 h/setm)</li>",
  "<li>Projecte intermodular (2 h/setm)</li>",
  "</ul>",
  "</div>",

  "</div>",
  '<p class="muted" style="margin-top:10px;">Font: Fitxa oficial GVA (CEICE) · <a href="https://ceice.gva.es/va/web/formacion-profesional/publicador-de-cicles/-/asset_publisher/M0SqOt5YOf05/content/ciclo-formativo-sistemas-microinformatico-y-redes" target="_blank" class="fitxa-oficial-link">Veure fitxa</a></p>',
  "</div>",
],

    requisits: [
  '<div class="panel-section requisits">',
  "<h3>🔑 Requisits d'accés</h3>",
  "<ul>",
  "<li>✅ ESO (Educació Secundària Obligatòria)</li>",
  "<li>✅ FP Bàsica (Grau Bàsic)</li>",
  "<li>✅ Prova d'accés a grau mitjà</li>",
  "<li>✅ Titulació superior (batxillerat, altres cicles…)</li>",
  "</ul>",
  "</div>",
],
   eixides: [
  '<div class="panel-section">',
  "<h3>💼 Eixides professionals</h3>",
  "<ul>",
  "<li>Tècnic  instal·lador-reparador d'equips informàtics</li>",
  "<li>Tècnic  de suport informàtic</li>",
  "<li>Tècnic  de xarxes de dades</li>",
  "<li>Reparador de perifèrics de sistemes microinformàtics</li>",
  "<li>Comercial de microinformàtica</li>",
  "<li>Operador de teleassistència</li>",
  "<li>Operador de sistemes</li>",
  "</ul>",
  "</div>",
],
    horari: [
  '<div class="panel-section">',
  "<h3>Horari de matí</h3>",
  "<ul>",
  "<li>De 08h a 15h</li>",
  "</ul>",
  "</div>",
],
    continu: [
  '<div class="panel-section">',
  '<h3>🚀 Continuïtat formativa</h3>',
  '<p>Accés directe als cicles formatius de grau superior:</p>',
  '<ul>',
  '<li>T.S. Administració de Sistemes Informàtics en Xarxa</li>',
  '<li>T.S. Desenvolupament d\'Aplicacions Multiplataforma</li>',
  '<li>T.S. Desenvolupament d\'Aplicacions Web</li>',
  '</ul>',
  '</div>'
],
    accent: "#6eb7c4",
  },

  dam: {
    titol: "Tècnic  Superior en Desenvolupament d'Aplicacions Multiplataforma",
    descripcio: "DAM",
    alerta:
      "Procés d'admissió: del 20/05 al 28/05<br>Matrícula telemàtica: del 20/07 al 27/07",
    eixides: [
  '<div class="panel-section">',
  "<h3>💼 Eixides professionals</h3>",
  "<ul>",
  "<li>Desenrotllar aplicacions informàtiques per a la gestió empresarial i de negoci</li>",
  "<li>Desenrotllar aplicacions de propòsit general</li>",
  "<li>Desenrotllar aplicacions en l'àmbit de l'entreteniment i la informàtica mòbil</li>",
  "</ul>",
  "</div>",
]
    ,requisits: [
   '<div class="panel-section requisits">',
  "<h3>🔑 Requisits d'accés</h3>",
  "<p>Es pot accedir amb:</p>",
  "<ul>",
  "<li>✅ Batxillerat</li>",
  "<li>✅ Títol de Tècnic  (Grau Mitjà)</li>",
  "<li>✅ Prova d'accés a Grau Superior</li>",
  "<li>✅ Un altre títol de Grau Superior</li>",
  "<li>✅ Titulació universitària</li>",
  "</ul>",
  "</div>",
],
pla: [
  '<div class="panel-section">',
  "<h3>📚 Pla de formació de 2000 hores</h3>",
  "<h4>· Incloses 500 h de Formació en Empresa</h4>",
  '<div class="plan-formacio">',

  '<div class="curs">',
  "<h4>1r curs</h4>",
  "<ul>",
  "<li>Inglés professional (GS) (2 h/setm)</li>",
  "<li>Llenguatges de marques i sistemes de gestió d'informació (3 h/setm)</li>",
  "<li>Sistemes informàtics (5 h/setm)</li>",
  "<li>Bases de dades (5 h/setm)</li>",
  "<li>Programació (8 h/setm)</li>",
  "<li>Entorns de desenvolupament (3 h/setm)</li>",
  "<li>Itinerari personal per a l'ocupabilitat I (3 h/setm)</li>",
  "<li>Projecte intermodular de desenvolupament d'aplicacions multiplataforma (1 h/setm)</li>",
  "</ul>",
  "</div>",

  '<div class="curs">',
  "<h4>2n curs</h4>",
  "<ul>",
  "<li>Accés a dades (4 h/setm)</li>",
  "<li>Desenvolupament d'interfícies (5 h/setm)</li>",
  "<li>Programació multimèdia i dispositius mòbils (4 h/setm)</li>",
  "<li>Programació de serveis i processos (2 h/setm)</li>",
  "<li>Sistemes de gestió empresarial (4 h/setm)</li>",
  "<li>Itinerari personal per a l'ocupabilitat II (3 h/setm)</li>",
  "<li>Projecte intermodular de desenvolupament d'aplicacions multiplataforma (3 h/setm)</li>",
  "<li>Mòdul optatiu (3 h/setm)</li>",
  "<li>Digitalització aplicada al sistema productiu (GS) (1 h/setm)</li>",
  "<li>Sostenibilitat aplicada al sistema productiu (1 h/setm)</li>",
  "</ul>",
  "</div>",

  "</div>",
  '<p class="muted" style="margin-top:10px;">Font: GVA (CEICE) · <a href="https://ceice.gva.es/es/web/formacion-profesional/publicador-de-cicles/-/asset_publisher/M0SqOt5YOf05/content/ciclo-formativo-desarrollo-de-aplicaciones-multiplataforma" target="_blank" rel="noopener noreferrer" class="fitxa-oficial-link">Fitxa oficial</a></p>',
  "</div>",
], horari: [
  '<div class="panel-section">',
  "<h3>Horari de matí</h3>",
  "<ul>",
  "<li>De 08h a 15h</li>",
  "</ul>",
  "</div>",
],continu: [
  '<div class="panel-section">',
  '<h3>🚀 Continuïtat formativa</h3>',
  '<p>Accés directe als cicles formatius de grau superior:</p>',
  '<ul>',
  '<li>T.S. Administració de Sistemes Informàtics en Xarxa</li>',
  '<li>T.S. Desenvolupament d\'Aplicacions Web (Amb convalidació de mòduls)</li>',
  '</ul>',
  '<p>Accés a graus universitaris:</p>',
  '<ul>',
  '<li>Accés sense fer la selectivitat específica</li>',
  "<li>Convalidació  d'assignatures (depèn de la universitat)</li>",
 '</ul>',
 '<p>Cursos d’especialització oficials:</p>',
  '<ul>',
  '<li>Ciberseguretat</li>',
  '<li>Intel·ligència artificial i Big Data</li>',
  '<li>Desenvolupament de videojocs</li>',
  '<li>Cloud computing</li>',
 '</ul>',

 '<p>Certificacions professionals:</p>',
  '<ul>',
  '<li>AWS, Azure o Google Cloud</li>',
  '<li>Cisco (xarxes)</li>',
  '<li>Oracle (Java, bases de dades)</li>',
  '<li>Microsoft (.NET, etc.)</li>',
 '</ul>',
  '</div>'
],
    accent: "#db8e5f",
      },


  daw: {
    titol: "Tècnic Superior en Desenvolupament d'Aplicacions Web",
    descripcio: "DAW",
    alerta:
      "Procés d'admissió: del 20/05 al 28/05<br>Matrícula telemàtica: del 20/07 al 27/07",
    eixides: [
  '<div class="panel-section">',
  "<h3>💼 Eixides professionals</h3>",
  "<ul>",
  "<li>Programador Web</li>",
  "<li>Programador Multimèdia</li>",
  "<li>Desenvolupador d'aplicacions en entorns Web</li>",
  "</ul>",
  "</div>",
],
    requisits: [
   '<div class="panel-section requisits">',
  "<h3>🔑 Requisits d'accés</h3>",
  "<p>Es pot accedir amb:</p>",
  "<ul>",
  "<li>✅ Batxillerat</li>",
  "<li>✅ Títol de Tècnic  (Grau Mitjà)</li>",
  "<li>✅ Prova d'accés a Grau Superior</li>",
  "<li>✅ Un altre títol de Grau Superior</li>",
  "<li>✅ Titulació universitària</li>",
  "</ul>",
  "</div>",
],
pla: [
  '<div class="panel-section">',
  "<h3>📚 Pla de formació de 2000 hores</h3>",
  "<h4>· Incloses 500 h de Formació en Empresa</h4>",
  '<div class="plan-formacio">',

  '<div class="curs">',
  "<h4>1r curs</h4>",
  "<ul>",
  "<li>Inglés professional (GS) (2 h/setm)</li>",
  "<li>Llenguatges de marques i sistemes de gestió d'informació (3 h/setm)</li>",
  "<li>Sistemes informàtics (5 h/setm)</li>",
  "<li>Bases de dades (5 h/setm)</li>",
  "<li>Programació (8 h/setm)</li>",
  "<li>Entorns de desenvolupament (3 h/setm)</li>",
  "<li>Itinerari personal per a l'ocupabilitat I (3 h/setm)</li>",
  "<li>Projecte intermodular de desenvolupament d'aplicacions web (1 h/setm)</li>",
  "</ul>",
  "</div>",

  '<div class="curs">',
  "<h4>2n curs</h4>",
  "<ul>",
  "<li>Desenvolupament web en entorn client (6 h/setm)</li>",
  "<li>Desenvolupament web en entorn servidor (6 h/setm)</li>",
  "<li>Desplegament d'aplicacions web (3 h/setm)</li>",
  "<li>Disseny d'interfícies web (4 h/setm)</li>",
  "<li>Itinerari personal per a l'ocupabilitat II (3 h/setm)</li>",
  "<li>Projecte intermodular de desenvolupament d'aplicacions web (3 h/setm)</li>",
  "<li>Mòdul optatiu (3 h/setm)</li>",
  "<li>Digitalització aplicada al sistema productiu (GS) (1 h/setm)</li>",
  "<li>Sostenibilitat aplicada al sistema productiu (1 h/setm)</li>",
  "</ul>",
  "</div>",

  "</div>",
  '<p class="muted" style="margin-top:10px;">Font: GVA (CEICE) · <a href="https://ceice.gva.es/es/web/formacion-profesional/publicador-de-cicles/-/asset_publisher/M0SqOt5YOf05/content/ciclo-formativo-desarrollo-de-aplicaciones-web" target="_blank" rel="noopener noreferrer" class="fitxa-oficial-link">Fitxa oficial</a></p>',
  "</div>",
], horari: [
  '<div class="panel-section">',
  "<h3>Horari de vesprada</h3>",
  "<ul>",
  "<li>De 15h a 21h</li>",
  "</ul>",
  "</div>",
],continu: [
  '<div class="panel-section">',
  '<h3>🚀 Continuïtat formativa</h3>',
  '<p>Accés directe als cicles formatius de grau superior:</p>',
  '<ul>',
  '<li>T.S. Administració de Sistemes Informàtics en Xarxa</li>',
  '<li>T.S. Desenvolupament d\'Aplicacions Multiplataforma (Amb convalidació de mòduls)</li>',
  '</ul>',
  '<p>Accés a graus universitaris:</p>',
  '<ul>',
  '<li>Accedés sense fer la selectivitat específica</li>',
  "<li>Convalidació  d'assignatures (depèn de la universitat)</li>",
 '</ul>',
 '<p>Cursos d’especialització oficials:</p>',
  '<ul>',
  '<li>Ciberseguretat</li>',
  '<li>Intel·ligència artificial i Big Data</li>',
  '<li>Desenvolupament de videojocs</li>',
  '<li>Cloud computing</li>',
 '</ul>',

 '<p>Certificacions professionals:</p>',
  '<ul>',
  '<li>AWS, Azure o Google Cloud</li>',
  '<li>Cisco (xarxes)</li>',
  '<li>Oracle (Java, bases de dades)</li>',
  '<li>Microsoft (.NET, etc.)</li>',
 '</ul>',
  '</div>'
],
  accent: "#a2433f",
  },

  fpb: {
    titol: "Formació Professional Bàsica.<br>Agrojardineria i Composicions Florals",
    descripcio: "FPB",
    alerta:
      "Procés d'admissió: del 25/05 al 02/06<br>Matrícula telemàtica: del 03/07 al 10/07",
    eixides: [
  '<div class="panel-section">',
  "<h3>💼 Eixides professionals</h3>",
  "<ul>",
  "<li>Peó agrícola</li>",
  "<li>Peó agropecuari</li>",
  "<li>Peó en horticultura</li>",
  "<li>Peó en fructicultura</li>",
  "<li>Peó en cultius herbacis</li>",
  "<li>Peó en cultius de flor cortada</li>",
  "<li>Peó de jardineria</li>",
  "<li>Peó de viver</li>",
  "<li>Peó de centres de jardineria</li>",
  "<li>Peó de camps esportius</li>",
  "<li>Peó de floristeria</li>",
  "<li>Auxiliar de floristeria</li>",
  "<li>Auxiliar de magatzem de flors</li>",
  "</ul>",
  "</div>",
],
    requisits: [
  '<div class="panel-section requisits">',
  "<h3>🔑 Requisits d'accés</h3>",
  "<ul>",
  "<li>✅ Tindre entre 15 i 17 anys</li>",
  "<li>✅ Haver cursat 3r d'ESO (o excepcionalment 2n)</li>",
  "<li>✅ Proposta de l'equip docent de l'institut</li>",
  "</ul>",
  "</div>",
],
   pla: [
  '<div class="panel-section">',
  "<h3>📚 Pla de formació (2000 hores)</h3>",
  "<h4>· Incloses 400 h de Formació en Empresa</h4>",
  '<div class="plan-formacio">',

  '<div class="curs">',
  "<h4>1r curs</h4>",
  "<ul>",
  "<li>Activitats de reg, adobat i tractaments en cultius (4 h/setm)</li>",
  "<li>Operacions auxiliars de preparació del terreny, plantació i sembra de cultius (3 h/setm)</li>",
  "<li>Operacions bàsiques de producció i manteniment de plantes en viveros i centres de jardineria (4 h/setm)</li>",
  "<li>Operacions auxiliars en l’elaboració de composicions amb flors i plantes (7 h/setm)</li>",
  "<li>Comunicació i Ciències Socials I (4 h/setm)</li>",
  "<li>Ciències Aplicades I (4 h/setm)</li>",
  "<li>Itinerari personal per a l’ocupabilitat I (2 h/setm)</li>",
  "<li>Tutoria 1r (2 h/setm)</li>",
  "</ul>",
  "</div>",

  '<div class="curs">',
  "<h4>2n curs</h4>",
  "<ul>",
  "<li>Operacions bàsiques en instal·lacions de jardins, parcs i zones verdes (5 h/setm)</li>",
  "<li>Operacions bàsiques per al manteniment de jardins, parcs i zones verdes (3 h/setm)</li>",
  "<li>Materials de floristeria (8 h/setm)</li>",
  "<li>Itinerari personal per a l’ocupabilitat II (1 h/setm)</li>",
  "<li>Comunicació i Ciències Socials II (5 h/setm)</li>",
  "<li>Ciències Aplicades II (5 h/setm)</li>",
  "<li>Projecte intermodular d’aprenentatge col·laboratiu (2 h/setm)</li>",
  "<li>Tutoria 2n (1 h/setm)</li>",
  "</ul>",
  "</div>",

  "</div>",
  '<p class="muted" style="margin-top:10px;">Font: GVA (CEICE) · <a href="https://ceice.gva.es/es/web/formacion-profesional/publicador-de-cicles/-/asset_publisher/M0SqOt5YOf05/content/formacion-profesional-basica-agrojardineria-y-composiciones-florales" target="_blank" rel="noopener noreferrer" class="fitxa-oficial-link">Fitxa oficial</a></p>',
  "</div>",
], horari: [
  '<div class="panel-section">',
  "<h3>Horari de matí</h3>",
  "<ul>",
  "<li>De 08h a 14h</li>",
  "</ul>",
  "</div>",
],continu: [
  '<div class="panel-section">',
  '<h3>🚀 Continuïtat formativa</h3>',
  '<p>Accés directe als cicles formatius de grau mitjà:</p>',
  '<ul>',
  '<li>T. Activitats Eqüestres</li>',
  '<li>T. Aprofitament i Conservació del Medi Natural</li>',
  '<li>T. Jardineria i Floristeria</li>',
  '<li>T. Producció Agroecològica</li>',
  '<li>T. Producció Agropecuària</li>',
  '</ul>',
  '</div>'
],
accent: "#a0c550",
  },

  pfqb: {
    titol: "Programa Formatiu de Qualificació Bàsica",
    descripcio: "PFQB",
    alerta:
      "Procés d'admissió: del 02/07/26 al 08/07/26<br>Matrícula: del 28/07/26 al 30/07/26",
  },

  ceiabd: {
    titol: "Curs d'Especialització de Inteligència Artificial i Big Data",
    descripcio: "CEIABD",
    alerta: "Procés d'admissió:<br> Del 25/05 al 02/06<br>MATRÍCULA PRESENCIAL:<br> Del 15/07 al 22/07",
    eixides: [
  '<div class="panel-section">',
  "<h3>💼 Eixides professionals</h3>",
  "<ul>",
  "<li>Desenvolupador d'Intel·ligència Artificial i Big Data</li>",
  "<li>Programador de sistemes experts</li>",
  "<li>Expert en Intel·ligència Artificial i Big Data</li>",
  "<li>Data Analyst (Analista de dades)</li>",
  "<li>Junior Data Scientist</li>",
  "<li>Data Engineer</li>",
  "</ul>",
  "</div>",
],
    requisits: [
   '<div class="panel-section requisits">',
  "<h3>🔑 Requisits d'accés</h3>",
  "<p>Es pot accedir si tens algun d'aquests títols:</p>",
  "<ul>",
  "<li>✅ Tècnic  Superior en Administració de Sistemes Informàtics en Xarxa</li>",
  "<li>✅ Tècnic  Superior en Desenvolupament d'Aplicacions Multiplataforma</li>",
  "<li>✅ Tècnic  Superior en Desenvolupament d'Aplicacions Web</li>",
  "<li>✅ Tècnic  Superior en Sistemes de Telecomunicacions i Informàtics</li>",
  "<li>✅ Títol de Tècnic  Superior en Mecatrònica Industrial</li>",
  "<li>✅ Títol de Tècnic  Superior en Automatització i Robòtica Industrial</li>",
  "</ul>",
  "</div>",
],
   pla: [
  '<div class="panel-section">',
  "<h3>📚 Pla de formació de 600 hores</h3>",
  "<h4>· Possibilitat de fer formació en empresa</h4>",
  '<div class="plan-formacio">',
  '<div class="curs">',
  "<h4>MÒDULS</h4>",
  "<ul>",
  "<li>Models d’intel·ligència artificial (3 h/setm)</li>",
  "<li>Sistemes d’aprenentatge automàtic (3 h/setm)</li>",
  "<li>Programació d’intel·ligència artificial (7 h/setm)</li>",
  "<li>Sistemes en Big Data (3 h/setm)</li>",
  "<li>Big Data aplicat (4 h/setm)</li>",
  "</ul>",
  "</div>",
  "</div>",
  '<p class="muted" style="margin-top:10px;">Font: GVA (CEICE) · <a href="https://ceice.gva.es/es/web/formacion-profesional/publicador-de-cursos-especialitzacio/-/asset_publisher/MRg14dkTb9DQ/content/inteligencia-artificial-y-big-data" target="_blank" rel="noopener noreferrer" class="fitxa-oficial-link">Fitxa oficial</a></p>',
  "</div>",
], horari: [
  '<div class="panel-section">',
  "<h3>Horari de vesprada</h3>",
  "<ul>",
  "<li>De 15h a 21h</li>",
  "</ul>",
  "</div>",
],continu: [
  '<div class="panel-section">',
  '<h3>🚀 Continuïtat formativa</h3>',
  "<p>Altres cursos d'especialització:</p>",
  '<ul>',
  '<li>Ciberseguretat</li>',
  '<li>Desenvolupament de videojocs</li>',
  '<li>Cloud computing</li>',
 '</ul>',

 '<p>Certificacions professionals:</p>',
  '<ul>',
  '<li>AWS (Machine Learning, Data Analytics)</li>',
  '<li>Microsoft Azure AI</li>',
  '<li>Google Cloud (Data Engineer, ML Engineer)</li>',
  '<li>TensorFlow o especialitzacions en Python</li>',
 '</ul>',
  '</div>'
], accent: "#a82f62",
  },
};
